interface WordDatum {
  content: string;
  isEnabled?: boolean;
}

const allWords: WordDatum[] = [
  { content: "a" },
  { content: "all", isEnabled: true },
  { content: "am", isEnabled: true },
  { content: "and" },
  { content: "are", isEnabled: true },
  { content: "as", isEnabled: true },
  { content: "at", isEnabled: true },
  { content: "away" },
  { content: "be", isEnabled: true },
  { content: "because" },
  { content: "big" },
  { content: "black" },
  { content: "blue" },
  { content: "brown" },
  { content: "but", isEnabled: true },
  { content: "by", isEnabled: true },
  { content: "came" },
  { content: "can" },
  { content: "come", isEnabled: true },
  { content: "could" },
  { content: "day", isEnabled: true },
  { content: "do" },
  { content: "eat", isEnabled: true },
  { content: "eight" },
  { content: "first" },
  { content: "five" },
  { content: "for" },
  { content: "four" },
  { content: "from", isEnabled: true },
  { content: "get", isEnabled: true },
  { content: "go" },
  { content: "got", isEnabled: true },
  { content: "green" },
  { content: "has", isEnabled: true },
  { content: "have" },
  { content: "he" },
  { content: "her" },
  { content: "here" },
  { content: "him" },
  { content: "his" },
  { content: "I" },
  { content: "in", isEnabled: true },
  { content: "is" },
  { content: "it", isEnabled: true },
  { content: "jump" },
  { content: "like" },
  { content: "little" },
  { content: "look" },
  { content: "love" },
  { content: "me", isEnabled: true },
  { content: "my", isEnabled: true },
  { content: "new" },
  { content: "nine" },
  { content: "no", isEnabled: true },
  { content: "not" },
  { content: "of", isEnabled: true },
  { content: "off" },
  { content: "on" },
  { content: "one" },
  { content: "out" },
  { content: "pink" },
  { content: "play" },
  { content: "purple" },
  { content: "red" },
  { content: "run" },
  { content: "said" },
  { content: "saw" },
  { content: "see" },
  { content: "seven" },
  { content: "she" },
  { content: "six" },
  { content: "so" },
  { content: "ten" },
  { content: "that", isEnabled: true },
  { content: "the" },
  { content: "then" },
  { content: "there", isEnabled: true },
  { content: "they", isEnabled: true },
  { content: "this", isEnabled: true },
  { content: "three", isEnabled: true },
  { content: "to" },
  { content: "too" },
  { content: "two" },
  { content: "up", isEnabled: true },
  { content: "us", isEnabled: true },
  { content: "want" },
  { content: "was", isEnabled: true },
  { content: "we", isEnabled: true },
  { content: "went" },
  { content: "what" },
  { content: "where", isEnabled: true },
  { content: "white" },
  { content: "who" },
  { content: "why" },
  { content: "with", isEnabled: true },
  { content: "yellow" },
  { content: "yes", isEnabled: true },
  { content: "you" },
  { content: "your" },
];

export const words = allWords.filter((w) => w.isEnabled).map((w) => w.content);

if (words.length < 24) {
  const numMissing = 24 - words.length;
  throw new Error(`Not enough words enabled. Need ${numMissing} more.`);
}
